# Generated by Django 3.2.3 on 2021-05-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
