# Generated by Django 3.2.3 on 2021-05-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usre',
            new_name='user',
        ),
    ]
