# Generated by Django 3.2.3 on 2021-05-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_usre_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Image',
            new_name='image',
        ),
    ]
